### ISSUE TITLE
No sending beacons

### ISSUE THREAD

**Issue by ebestek** [helium/erlang-libp2p#407] opened 2021-12-06 06:37 UTC
![image](https://user-images.githubusercontent.com/95607188/144797907-5329e835-dd46-4934-b8e7-03e8577ecf80.png)

After the 04.11.2021 update, there is no send beacons for 30 days.  For solution, i changed the static ip to new 2 times, however there is no change. It started to getting annoying. How i can fix this problem or will there be uptade for fixing and when?

**Comment by madninja** [comment] 2021-12-06 14:13
Duplicate of https://github.com/helium/miner/issues/1279. Please do not post issues in multiple repos

**Closed by madninja** 2021-12-06 14:13 UTC
